### ISSUE TITLE
Proposed Hierarchy

### ISSUE THREAD

**Issue by elovero** [flatironinstitute/astrosims#12]
# Astrosims Hierarchy

## Milky Way

    - Gaia DR2
    - Ananke

## Cosmological Galaxy Formation Simulations

_all contain several simulations with 2 catalogs (halos / subhalos)_

- Illustris TNG
- Illustris
- Simba
- (tbd others)
- GAEA ??

## Cosmological Dark Matter-Only Simulations

    - Quixote (is vast)
    - Illustris
    - (tbd others, including the ones shown)

## CANDELS

    - SC-SAM
    - UniverseMachine
    - Lu-SAM
    - CANDELS observational data

## Cosmological Zoom-in Simulations

    - FIRE

**Comment by dylex** [comment]
Added to catalogs.yml.
