### ISSUE TITLE
Download plot data on catalog page

### ISSUE THREAD

**Issue by lizlove** [flatironinstitute/astrosims#46]
- Perhaps integrate in the highcharts ?
- Can this be done on the front end?

**Comment by dylex** [comment]
Built in to highcharts!  Some minor issues:

- [ ] Context menu overflows hist div and gets cut off.
- [ ] "View data table" option shows data but it never goes away. I think a button that just removes all "highcharts-data-table" divs would work.

**Comment by lizlove** [comment]
See: #68

**Comment by lizlove** [comment]
@lizlove to remove the option from dropdown .... see highcharts?
