### ISSUE TITLE
Python module numpy() function times out nearly 100% of the time

### ISSUE THREAD

**Issue by aust427** [flatironinstitute/astrosims#9]
Title is self explanatory, prevents the user from downloading the data as a numpy array. All other functions seem to be working fine though (count(), hist(), aggs(), etc.) 
![image](https://user-images.githubusercontent.com/10734103/47109161-8f01a600-d21b-11e8-9b9a-a17d4af4a448.png)

**Comment by dylex** [comment]
I haven't been able to reproduce this on the new production server...

**Comment by dylex** [comment]
also recently increased the timeout on the server.
